-- The boot self-test battery, as a package.
--
-- The runner has always been in the base image (tos/kernel/selftest.lua);
-- the checks lived on a test disk. This installs them into
-- /usr/lib/selftest/, which the runner already searches, plus the
-- `selftest` command that arms, disarms, lists and reads a run.
--
-- Installing it needs ROOT: an armed machine runs every check in
-- /usr/lib/selftest/ inside the kernel, so pkg holds any package that
-- puts a file there to the service package's root gate.
return {
  -- Generated by build-disk.lua (package integrity)
  hashes = {
    ["/usr/lib/selftest/10-boot.lua"] = "3d0c22c6f9027b0743678dd12883238cb05db25516600369c61ae6bdc140cfa9",
    ["/usr/lib/selftest/20-display.lua"] = "8552faee391f21f4873f414d19683accb009bf12180bcc8fd95e0d4b44e15e21",
    ["/usr/lib/selftest/30-hash-at-size.lua"] = "ec99997648275e40bf3bb7e6ef46c5f03a97617af7de24caa23d75a46a7d4d25",
    ["/usr/lib/selftest/40-fs-roundtrip.lua"] = "0d21943e664c3a35aca448055527eff783832ef908cc4d42620effaa3ec40323",
    ["/usr/lib/selftest/50-srm.lua"] = "8a3cb7513731d58b35a915cd1d060e234cebff9a114663b88d4e2116bc7ad97f",
    ["/usr/lib/selftest/60-sandbox.lua"] = "8dd3b42b2e5eebcf8a979be69ce209a8b1f5a4547b3e44d3642a71ed7716f9bf",
    ["/usr/lib/selftest/70-screen-truth.lua"] = "12802e030dc8cd4bfbc1e901b0c2bf7f30dcb7496f8ef392ba64f4d31aaff91e",
    ["/usr/lib/selftest/80-pkg-signing.lua"] = "02fc24b02f3b58a0b4cfd08e70a8a9ccd2db680185363ae01b19f0d511249454",
    ["/usr/lib/selftest/90-internet-absence.lua"] = "991c5385d5f2931c9b97421d30fc020161af1e00c2dd014190294787465140bf",
    ["/usr/lib/selftest/91-keyboard.lua"] = "4220e0bfc1edd0a32caccbd5e270bd1f9bb972935f4226a2382b989874fed939",
    ["/usr/lib/selftest/92-term.lua"] = "ffac937c5c9d1ee00a739cc43531a316b814accaadcd09c91c5bb8aa83a736f4",
    ["/usr/lib/selftest/93-audio.lua"] = "79170f0aad0120d866e0cf079a4ce3d0adf2d5a94ee8ecd2d841596073ea6adc",
    ["/usr/lib/selftest/94-rename-truth.lua"] = "552541a31505b0f05fa6a7130c57831c1ece77b6f5260634675258e87a1a70fb",
    ["/usr/lib/selftest/95-utf8-tokens.lua"] = "40f8a62e1bf1808a7ae0a2f112d00b3dbaebff30d1f6c1570f808e2ab4feace6",
    ["/usr/lib/selftest/96-waitfor.lua"] = "8d8e808ef2c655263447638a6e0d1810d4cf85868bd0e61ed2df2b569e258797",
    ["/usr/lib/selftest/97-inprocess.lua"] = "874b34e9a5ca5e73ac1a1ee71a8323205844f93468783a36f175b982e871ea48",
    ["/usr/modules/selftest/init.lua"] = "41ffdf92d094877ee9e72c7785c3334a9a61c20eee880e327e62dc02da1d5486",
  },
  name        = "selftest",
  -- 1.0.0 -- the battery as it stood on 2026-10-02: sixteen checks, 10-boot
  -- through 97-inprocess, and the `selftest` command.
  version     = "1.0.0",
  kind        = "command",
  category    = "dev",
  -- One string literal, not "a" .. "b": pkg reads this file with the
  -- kernel's data-only decoder, which refuses any expression.
  description = "Boot self-test battery: checks that run inside the booted kernel on real hardware, and `selftest` to arm, list and read them. For testing your own additions to TOS. Root install.",
  author      = "Strata Systems",
  files       = {
    "/usr/modules/selftest/init.lua",
    "/usr/lib/selftest/10-boot.lua",
    "/usr/lib/selftest/20-display.lua",
    "/usr/lib/selftest/30-hash-at-size.lua",
    "/usr/lib/selftest/40-fs-roundtrip.lua",
    "/usr/lib/selftest/50-srm.lua",
    "/usr/lib/selftest/60-sandbox.lua",
    "/usr/lib/selftest/70-screen-truth.lua",
    "/usr/lib/selftest/80-pkg-signing.lua",
    "/usr/lib/selftest/90-internet-absence.lua",
    "/usr/lib/selftest/91-keyboard.lua",
    "/usr/lib/selftest/92-term.lua",
    "/usr/lib/selftest/93-audio.lua",
    "/usr/lib/selftest/94-rename-truth.lua",
    "/usr/lib/selftest/95-utf8-tokens.lua",
    "/usr/lib/selftest/96-waitfor.lua",
    "/usr/lib/selftest/97-inprocess.lua",
  },
  commands     = { selftest = "/usr/modules/selftest/init.lua" },
  -- fs.read for the log, the checks and the marker; fs.write for the
  -- marker, which securefs lets only root write.
  capabilities = { "fs.read", "fs.write" },
}
