-- Optional Utilities — snake: classic snake with per-user high scores.
--
-- Its own standalone package (operator's model: each program is
-- individually installable — you can take snake without ttt or tetris).
-- Grouped with them under category="games" so the installer can offer
-- the games together while still letting you pick just one.
--
-- Sandbox-safe: draws through the sandboxed `component` GPU proxy, pulls
-- raw signals, writes its high-score board through the session-bound
-- `fs`. Rules are pure in snake/logic.lua, unit-tested by test_snake.lua.
--
-- 1.0.1 — the board really is per player: scores go to .snake_hs in the
-- player's own home (fs.home()), not to /home/.snake_hs, which admins
-- shared and ordinary users could not write. test_snake_scores.lua.
return {
  -- Generated by build-disk.lua (package integrity)
  hashes = {
    ["/usr/modules/snake/init.lua"] = "30a182ec62bad41a51933234078abc08ae26df5e086887df4aecccce9cc31c60",
    ["/usr/modules/snake/logic.lua"] = "1f80f571f2571df1d0797ccf59507d12cdd8ba74ff2b34640ef4f838d5d14e89",
  },
  name        = "snake",
  version     = "1.0.1",
  kind        = "command",
  category    = "games",
  description = "Classic snake with per-user high scores. Requires a T2+ screen.",
  author      = "Strata Systems",
  files       = {
    "/usr/modules/snake/init.lua",
    "/usr/modules/snake/logic.lua",
  },
  -- Full-screen program: the shell hands it the seat as its own
  -- process, so Ctrl+B can push it to the background and Ctrl+T
  -- brings it back instead of it owning the terminal until it exits.
  fullscreen  = true,
  -- Background policy (freeze): a snake that kept moving while you were in the shell
  -- would be dead when you came back.
  background  = "freeze",

  commands     = { snake = "/usr/modules/snake/init.lua" },
  capabilities = { "fs.read", "fs.write", "component" },
  requires    = {},
}
