-- FEAT-7 native package manifest for tetris.
-- The legacy `module.cfg` is kept for back-compat; pkg.install prefers
-- this file when both are present.
return {
  -- Generated by build-disk.lua (package integrity)
  hashes = {
    ["/usr/modules/tetris/init.lua"] = "d833521b8562cda209540fde19fb7e34c71257a1a665e10cb2a9fe4b3a2b2d77",
  },
  name        = "tetris",
  -- 1.1.1 — fix multi-line clears. Completing 2+ rows at once cleared the
  -- WRONG rows (the lock loop interleaved remove+insert, shifting indices),
  -- leaving completed lines on the board — "they clear one at a time".
  -- Line clearing is now a pure, unit-tested pair (fullRows/removeRows).
  -- 1.1.0 — runs fully inside the pkg sandbox (draws via the component
  -- GPU proxy, scores via the session-bound fs). The 1.0.0 build still
  -- required kernel.display/kernel.event, which pkg blocks, so the
  -- game could not launch at all after the kernel.modules→pkg pivot.
  version     = "1.1.1",
  kind        = "command",
  category    = "games",
  description = "Classic Tetris with per-user high scores. Requires a T2+ screen.",
  author      = "Strata Systems",
  files       = {
    "/usr/modules/tetris/init.lua",
  },
  -- Full-screen program: the shell hands it the seat as its own
  -- process, so Ctrl+B can push it to the background and Ctrl+T
  -- brings it back instead of it owning the terminal until it exits.
  fullscreen  = true,
  -- Background policy (freeze): a falling piece must not keep falling while the
  -- operator is looking at something else.
  background  = "freeze",

  commands     = { tetris = "/usr/modules/tetris/init.lua" },
  capabilities = { "fs.read", "fs.write", "component" },
  requires    = {},
  -- Tetris reads mouse clicks for rotate/drop when the driver is there.
  recommends  = { "mouse" },
}
