-- Optional Utilities — write: a word processor for TOS.
--
-- TOS already ships `edit`. This is not a second text editor: the
-- difference is the PAGE. `write` knows how wide a printed line is in
-- pixels, how many lines fit on a sheet, and therefore where the
-- document breaks — live, in the rail, while you type — plus what it
-- will cost in paper and ink before you spend either.
--
-- WHY IT REQUIRES `printer` RATHER THAN RECOMMENDING IT.
-- The page model (widths, wrapping, pagination, costing) lives in the
-- driver's /usr/lib/printerfmt.lua. Without it there is no page, and a
-- word processor with no page is `edit` with extra steps — so this is a
-- real dependency and is declared as one. The picker will auto-select
-- `printer` alongside it and say so.
--
-- The printer HARDWARE is a different question and is deliberately soft:
-- composing, paginating, the page view and saving all work on a machine
-- with no printer in the world. The rail says whether the page breaks
-- came from the attached printer's own metrics or from the driver's
-- transcribed width table, because an estimated break and a real one are
-- not equally trustworthy and the operator should be told which they are
-- looking at.
--
-- THE FILE FORMAT IS PLAIN TEXT. Formatting rides on dot commands in
-- column one (.title .center .color .page), the roff idiom: greppable,
-- hand-editable, mailable, and never executable — the same argument calc
-- makes for not building its formulas on load().
--
-- The document model (write/doc.lua) is pure and unit-tested off-box by
-- modules/write/test_write.lua.
return {
  -- Generated by build-disk.lua (package integrity)
  hashes = {
    ["/usr/modules/write/doc.lua"] = "c0339d0fcd701b49a5b238175d0f0850699e0841a281b8db9d0f4f6e39ad9e40",
    ["/usr/modules/write/init.lua"] = "d2f83a82bef0caac5d3b248952c6225f9ec4b30a94c677a98b5d622b0de2931e",
  },
  name        = "write",
  version     = "1.0.0",
  kind        = "command",
  category    = "productivity",
  description = "Word processor: live page breaks, ink/paper cost, dot-command formatting, prints via the printer driver.",
  author      = "Strata Systems",
  files       = {
    "/usr/modules/write/init.lua",
    "/usr/modules/write/doc.lua",
  },
  -- Full-screen program: the shell hands it the seat as its own process,
  -- so Ctrl+B pushes it to the background and Ctrl+T brings it back.
  fullscreen  = true,
  -- Background policy (freeze): an editor holds UNSAVED WORK. Nothing
  -- about a backgrounded document should keep moving — no timers, no
  -- relayout, nothing that could touch the buffer while the operator is
  -- not looking at it. This is the opposite call from stock's "drowsy",
  -- and for the opposite reason: stock loses nothing by refreshing, and
  -- an editor can lose everything.
  background  = "freeze",

  commands     = { write = "/usr/modules/write/init.lua" },
  -- fs for documents, component for the GPU, peripheral.printer to
  -- actually print. No `load` (a document is never executed), no `net`,
  -- no `internet` — this writes files and paper, it has nobody to tell.
  capabilities = { "fs.read", "fs.write", "component", "peripheral.printer" },
  requires    = { "printer" },
  -- Soft: the editor is keyboard-first and complete without a mouse.
  recommends  = { "mouse" },
}
