-- ╔══════════════════════════════════════════════════════════╗
-- ║  Regression Test: TODO.txt's OPEN QUEUE is not stale       ║
-- ║                                                            ║
-- ║  TODO.txt carries a GENERATED index of its open entries,   ║
-- ║  because the file is 3,200 lines of round-by-round history ║
-- ║  and the open work was invisible inside it. An index that   ║
-- ║  drifts is worse than none: it looks authoritative and      ║
-- ║  isn't, which is the same failure the file already had.     ║
-- ║                                                            ║
-- ║  So the index is generated by todo_index.py and this asks   ║
-- ║  that script whether it is current, rather than            ║
-- ║  re-implementing the parse and drifting from it in a        ║
-- ║  second place. Same rule test_rc_kernel_claim.lua follows   ║
-- ║  for rc.lua's allowlist: read the real thing, never a copy. ║
-- ╚══════════════════════════════════════════════════════════╝
-- Run: lua usr/lib/tests/test_todo_index.lua

local passed, failed = 0, 0
local function test(name, cond)
  if cond then passed = passed + 1; print("  PASS: " .. name)
  else failed = failed + 1; print("  FAIL: " .. name) end
end

print("=== TODO index Tests ===")
print()

-- The suite runs with cwd = TOS-Dev, which is where both files live.
local function fileExists(p)
  local fh = io.open(p, "r")
  if fh then fh:close(); return true end
  return false
end

if not fileExists("todo_index.py") or not fileExists("TODO.txt") then
  print("  SKIP: not run from TOS-Dev; skipping (run inside TOS-Dev)")
  print("Results: 0 passed, 0 failed")
  print("All tests passed.")
  return true
end

test("todo_index.py is present", true)
test("TODO.txt is present", true)

-- Ask the generator. Exit 1 means the block does not match what the
-- current markers would produce.
--
-- The CODE has to be read, not just the first return value: Lua 5.4's
-- os.execute yields `nil, "exit", <code>` for ANY non-zero exit, so
-- testing `ok == nil` alone cannot tell "the index is stale" (1) from
-- "there is no python here" (127). Written that way first, and the
-- result was a test that skipped itself precisely when it had something
-- to report.
local ok, how, code = os.execute("python todo_index.py --check")
local succeeded = (ok == true) or (ok == 0) or (code == 0)
local missing = (code == 127 or code == 126)

if missing then
  -- A missing interpreter is an environment fact, not a stale index.
  -- Conflating them would train people to ignore this test.
  print("  SKIP: python not available; cannot verify the index")
else
  test("OPEN QUEUE block matches the markers in TODO.txt "
    .. "(if this fails: python todo_index.py)", succeeded)
end

-- The block must actually be in the file — a generator that silently
-- stopped emitting would otherwise "pass" forever.
do
  local fh = io.open("TODO.txt", "r")
  local body = fh:read("*a")
  fh:close()
  test("the OPEN QUEUE block exists",
    body:find("=== OPEN QUEUE", 1, true) ~= nil)
  test("...and is closed",
    body:find("=== end OPEN QUEUE ===", 1, true) ~= nil)
  -- It has to say something. An empty index is the drift case that
  -- would otherwise read as "no open work".
  local blk = body:match("=== OPEN QUEUE.-=== end OPEN QUEUE ===")
  test("the block is non-trivial", blk ~= nil and #blk > 200)
  test("...and lists at least one entry",
    blk ~= nil and blk:find("L%d") ~= nil)
end

print()
print(string.format("Results: %d passed, %d failed", passed, failed))
if failed > 0 then print("*** TESTS FAILED ***"); return false
else print("All tests passed."); return true end
