-- FEAT-13 — host-side controller for the rc-pilot EEPROM.
-- Run on a TOS computer with a wireless modem. Captures WASD/arrows/
-- Space/Shift and forwards them to the targeted robot.
return {
  -- Generated by build-disk.lua (package integrity)
  hashes = {
    ["/usr/modules/rc-pilot/init.lua"] = "99295d5f52c2b0f8579b3a841d9f64ee83b96adf92f5316c98449ec14cac2e26",
  },
  name        = "rc-pilot",
  version     = "1.1.0",
  kind        = "command",
  category    = "control",
  description = "WASD remote-control host for OC robots/drones running the rc-pilot EEPROM.",
  author      = "Strata Systems",
  files       = {
    "/usr/modules/rc-pilot/init.lua",
  },
  commands     = { rc = "/usr/modules/rc-pilot/init.lua" },
  -- "crypto" injects the narrow hmac/random surface the frame signer needs;
  -- without it the sandbox leaves `crypto` nil and `rc` fails on first use.
  capabilities = { "fs.read", "fs.write", "component", "peripheral.modem", "crypto" },
  requires    = {},
}
