-- Optional Utilities — ttt: tic-tac-toe against an unbeatable AI.
--
-- Its own standalone package (operator's model: each program is
-- individually installable). Grouped with snake + tetris under
-- category="games" so the installer offers the games together while
-- still letting you take just one.
--
-- Sandbox-safe (component GPU proxy + raw signals). The RULES live in
-- ttt/logic.lua — pure, unit-tested by test_ttt.lua, which proves the AI
-- is genuinely unbeatable by exhaustively playing every human line.
--
-- `ttt` also hides an undocumented mode that makes the OS's own easter
-- egg findable without reading source. Deliberately not described here
-- or in the help bar — finding it is the point. (It is photosensitivity-
-- safe and pinned by tests, including one asserting the command it
-- reveals is still the command the base image actually listens for.)
return {
  -- Generated by build-disk.lua (package integrity)
  hashes = {
    ["/usr/modules/ttt/init.lua"] = "9a87257d68d9f66e6d8ef2f6112b0e6effea0ff270d7d4f18fee54b1f4cf5472",
    ["/usr/modules/ttt/logic.lua"] = "3c898ee3f4ba51961266c99b2440ebe1eb16c26aa32a68fc31e78bc3e6debdfa",
  },
  name        = "ttt",
  version     = "1.0.0",
  kind        = "command",
  category    = "games",
  description = "Tic-tac-toe vs an unbeatable AI, or 2-player. Requires a T2+ screen.",
  author      = "Strata Systems",
  files       = {
    "/usr/modules/ttt/init.lua",
    "/usr/modules/ttt/logic.lua",
  },
  -- Full-screen program: the shell hands it the seat as its own
  -- process, so Ctrl+B can push it to the background and Ctrl+T
  -- brings it back instead of it owning the terminal until it exits.
  fullscreen  = true,
  -- Background policy (drowsy): nothing moves unless you move it, so the default is fine.
  background  = "drowsy",

  commands     = { ttt = "/usr/modules/ttt/init.lua" },
  capabilities = { "fs.read", "fs.write", "component" },
  requires    = {},
  -- ttt is click-to-play when the mouse driver is installed.
  recommends  = { "mouse" },
}
