-- CLUSTER-3 — installable manifest for the cluster Manager daemon.
-- One Manager per "compute node" — the machine that actually runs
-- workers. Registers with the Master at startup and accepts
-- assignments. The Master schedules; the Manager executes.
--
-- Topology:
--   [TOS Master]
--    └ via wireless modem ─► [TOS Manager(s)]
--                              └ via worker port 2001+domain_id ─►
--                                   [OpenOS worker(s)] (or local TOS workers)
--
-- The OpenOS worker code is at TOS-Extras/cluster/openos/cluster-worker.lua
-- — that side is OpenOS-native because OpenOS robots and computers are
-- much more common in OC and worker code wants the wider library
-- surface (printable terminals, easy file I/O).
return {
  -- Generated by build-disk.lua (package integrity)
  hashes = {
    ["/etc/cluster-manager.cfg"] = "b063b8763256ff9b1d52466934ce0d472773c3ded43d3466b5bf0bab2464cd0e",
    ["/etc/rc.d/cluster-manager.lua"] = "01a71ed0ec114c0520857b0b6879a89e9ccad4d437d51ab9e705dc1720f11bb7",
    ["/usr/bin/cluster-manager.lua"] = "82337a87cc3d9bd15700e701c3cbb6dfd7f6e2c4b7fd2343e9526ff295470d7a",
    ["/usr/lib/cluster-manager.lua"] = "268704430e5dcaf070ef52eb3757d1a9b96fcb7d63e8972ad8b122a8fb6118f8",
    ["/usr/lib/cluster/protocol.lua"] = "b5d7160e5c323d2624c714e72e9a588de970da9d1b8fd28e59abf0f43e76032b",
    ["/usr/lib/cluster/worker.lua"] = "a36b6d89c7e8fd59419cb7773e221025ea4f8871ae9d50c065afd975deae46bb",
  },
  name        = "cluster-manager",
  version     = "1.2.1",
  kind        = "service",
  category    = "network",
  description = "Cluster Manager: registers with Master, accepts assignments, dispatches to workers.",
  author      = "Strata Systems",
  files       = {
    "/usr/lib/cluster-manager.lua",
    "/usr/bin/cluster-manager.lua",
    "/etc/rc.d/cluster-manager.lua",
    "/etc/cluster-manager.cfg",
    -- Cluster protocol core + Manager↔OpenOS-Worker bridge. These moved
    -- out of the base kernel (kernel/net/) so the cluster code ships only
    -- with this optional package. worker.lua is wired into the daemon when
    -- the bridge path is enabled (worker_bridge_address set); the daemon
    -- otherwise runs tasks inline.
    "/usr/lib/cluster/protocol.lua",
    "/usr/lib/cluster/worker.lua",
  },
  --! cluster-storage declares `requires = { "cluster-protocol" }`, and no
  --! package by that name has ever existed -- so `pkg install
  --! cluster-storage` would fail resolution on a dependency nobody could
  --! satisfy. It has not bitten yet only because cluster-storage is 0.1.0
  --! and the pack excludes anything below 1.0.0.
  --!
  --! `provides` is the mechanism already used for tape/tape-storage, and
  --! it makes the existing declaration resolve to the package that really
  --! ships /usr/lib/cluster/protocol.lua -- this one. It is a bandage over
  --! a packaging question, not an answer to it: a Storage Node should not
  --! have to install a whole Manager daemon to get the wire format. The
  --! real fix is a small `cluster-protocol` package, recorded in TODO.txt.
  provides    = { "cluster-protocol" },
  -- No `commands` map: the operator CLI ships as /usr/bin/cluster-manager.lua
  -- and is run from PATH at full shell privilege (the package sandbox would
  -- withhold the live kernel net/component surface it needs). Omitted on
  -- purpose, like /usr/bin/servers, ssh — not registered as a package command.
  capabilities = {
    "fs.read", "fs.write",
    "component",
    "peripheral.modem",
    "net",
    "load",                     -- evaluating task code from the Master
    "compat.io",                -- worker-bridge writes
  },
  service = { defaultState = "disabled" },
  requires = {},
}
