-- CLUSTER-2 — installable manifest for the cluster Master daemon.
-- Run `pkg install cluster-master` after copying this directory tree
-- to a TOS repo location. The Master is the control-plane node; each
-- network should have exactly one. Multiple Masters would each accept
-- registrations independently and the cluster would partition.
--
-- Requires:
--   * A wireless modem (or a wired modem connected to every Manager).
--   * ROOT tier to operate the CLI's mutating subcommands.
--   * The `cluster-master` rc.d service stays disabled by default;
--     enable with `service start clusterd` after first install so an
--     accidentally-installed binary doesn't immediately start
--     advertising itself.
return {
  -- Generated by build-disk.lua (package integrity)
  hashes = {
    ["/etc/cluster-master.cfg"] = "42517c61f940ec779cc9863b185135b5146c49170600964daba979afe03f744d",
    ["/etc/rc.d/clusterd.lua"] = "ae427b59a6012912b1a11016fc4acf1f70f7e3c78ef52f244d54d561faaa8b6f",
    ["/usr/bin/cluster.lua"] = "0a87c2b4baa3361e40987e0b04aee26847fbf9fec4969d1e3a98bf6c67068888",
    ["/usr/lib/cluster/api.lua"] = "2216ad483d5d0db5f5d178086a6d90b7ed47ec7b63715fd0e7c7a111be8c7785",
    ["/usr/lib/cluster/jobs.lua"] = "8c1cac3b330002383b9e754d705ee6a9c3e48ddc50c44719423d84e8c4e23a61",
    ["/usr/lib/cluster/net.lua"] = "8d91120ba6f28f7225905659622f93318bd84ce9a440ac1c28247cae0e59e4bb",
    ["/usr/lib/cluster/pair.lua"] = "0bf98212ae96293d5aaaf087e3a5cb79c852a79a8790890e58f5948d0e4b7762",
    ["/usr/lib/cluster/scheduler.lua"] = "364fd2bf2db85c6cdf5c0f7c63870849528958984af9912db5a4e2e2516826a5",
    ["/usr/lib/cluster/state.lua"] = "abcc25dd5764208ce55a1c1abc6f5e7d95fc27f4c6a1a976d0c9a212b34c174f",
    ["/usr/lib/cluster/store_client.lua"] = "7db025f088acd6309264a12f734dc70127d8ea5430d8949ece8adf2f7cab1582",
    ["/usr/lib/clusterd.lua"] = "1a51fc1eccefab6293a56c5013c461dfbb9855b99351b311fac77df51c835fb0",
  },
  name        = "cluster-master",
  version     = "1.0.2",
  kind        = "service",
  category    = "network",
  description = "Cluster control-plane Master: registers Managers, schedules jobs, owns persistent state.",
  author      = "Strata Systems",
  files       = {
    "/usr/lib/clusterd.lua",
    "/usr/lib/cluster/state.lua",
    "/usr/lib/cluster/scheduler.lua",
    "/usr/lib/cluster/jobs.lua",
    "/usr/lib/cluster/net.lua",
    "/usr/lib/cluster/api.lua",
    "/usr/lib/cluster/pair.lua",
    -- clusterd.lua requires this at load, unguarded. Leaving it out of
    -- the list did not break anything HERE, where it sits beside the
    -- others in the source tree; it broke the INSTALLED package, whose
    -- daemon died on `require("cluster.store_client")`.
    "/usr/lib/cluster/store_client.lua",
    "/usr/bin/cluster.lua",
    "/etc/rc.d/clusterd.lua",
    "/etc/cluster-master.cfg",
  },
  -- No `commands` map: the operator CLI ships as /usr/bin/cluster.lua and is
  -- run from PATH at full shell privilege (it needs the live kernel net/
  -- component surface, which the package sandbox would withhold). Declaring it
  -- as a package command would either be malformed (array form) or sandbox the
  -- CLI — so it is intentionally omitted, exactly like /usr/bin/servers, ssh.
  capabilities = {
    "fs.read", "fs.write",      -- /etc/cluster-master.cfg + /var/cluster/state.dat
    "component",                -- modem listing
    "peripheral.modem",         -- C4 split: cluster needs raw modem access
    "net",                      -- TOS net stack
    "load",                     -- evaluating job specs at submit time
  },
  -- The rc.d hook starts the daemon. defaultState=disabled so a fresh
  -- install doesn't auto-start a service on every machine that gets
  -- the package — operator decides per-host.
  service = { defaultState = "disabled" },
  requires    = {},
  -- FEAT-14: no license needed; this is the open control-plane.
}
