-- CLUSTER-2 — installable manifest for the cluster Master daemon.
-- Run `pkg install cluster-master` after copying this directory tree
-- to a TOS repo location. The Master is the control-plane node; each
-- network should have exactly one. Multiple Masters would each accept
-- registrations independently and the cluster would partition.
--
-- Requires:
--   * A wireless modem (or a wired modem connected to every Manager).
--   * ROOT tier to operate the CLI's mutating subcommands.
--   * The `cluster-master` rc.d service stays disabled by default;
--     enable with `service start clusterd` after first install so an
--     accidentally-installed binary doesn't immediately start
--     advertising itself.
return {
  -- Generated by build-disk.lua (package integrity)
  hashes = {
    ["/etc/cluster-master.cfg"] = "42517c61f940ec779cc9863b185135b5146c49170600964daba979afe03f744d",
    ["/etc/rc.d/clusterd.lua"] = "52eb4457610f8e1005bf3aae11573219e38738d85a8eba18304b470fb3ec496b",
    ["/usr/bin/cluster.lua"] = "7786678b993d81db6def34bda4e2412fb8bf4fd7e0791dc2e27b63572ab8d324",
    ["/usr/lib/cluster/api.lua"] = "c20712b0c7cc160b444f03d293fe53d0a9476717161899297b470ac5540c568b",
    ["/usr/lib/cluster/jobs.lua"] = "2bfd3f20f98f86718af51dcebfd4cdbd48a36022b7740013be7f9845e0bad461",
    ["/usr/lib/cluster/net.lua"] = "efc81475aa0c746dc2104e4c1df6b2853e16efb6afd1cb12b829e2a9ccb64c6e",
    ["/usr/lib/cluster/pair.lua"] = "74802c4d28ff417173ea22a3638aecdc419bebf8ab16b0a3deeabaec6ede14c1",
    ["/usr/lib/cluster/scheduler.lua"] = "7d3ce7f9d345653e95e3124600d0a4c07a572f52fc2c46815cec480a65ea732d",
    ["/usr/lib/cluster/state.lua"] = "456ad8feccb5c1b96e1563cad460eaedda4b82ef925207f223ac409fe3a4eb50",
    ["/usr/lib/clusterd.lua"] = "ddb9a7d4ccff6191d9ef6ff634f882db1bac224157926b7fc6cbc5235eabddfe",
  },
  name        = "cluster-master",
  version     = "1.0.0",
  kind        = "service",
  category    = "network",
  description = "Cluster control-plane Master: registers Managers, schedules jobs, owns persistent state.",
  author      = "Strata Systems",
  files       = {
    "/usr/lib/clusterd.lua",
    "/usr/lib/cluster/state.lua",
    "/usr/lib/cluster/scheduler.lua",
    "/usr/lib/cluster/jobs.lua",
    "/usr/lib/cluster/net.lua",
    "/usr/lib/cluster/api.lua",
    "/usr/lib/cluster/pair.lua",
    "/usr/bin/cluster.lua",
    "/etc/rc.d/clusterd.lua",
    "/etc/cluster-master.cfg",
  },
  -- No `commands` map: the operator CLI ships as /usr/bin/cluster.lua and is
  -- run from PATH at full shell privilege (it needs the live kernel net/
  -- component surface, which the package sandbox would withhold). Declaring it
  -- as a package command would either be malformed (array form) or sandbox the
  -- CLI — so it is intentionally omitted, exactly like /usr/bin/servers, ssh.
  capabilities = {
    "fs.read", "fs.write",      -- /etc/cluster-master.cfg + /var/cluster/state.dat
    "component",                -- modem listing
    "peripheral.modem",         -- C4 split: cluster needs raw modem access
    "net",                      -- TOS net stack
    "load",                     -- evaluating job specs at submit time
  },
  -- The rc.d hook starts the daemon. defaultState=disabled so a fresh
  -- install doesn't auto-start a service on every machine that gets
  -- the package — operator decides per-host.
  service = { defaultState = "disabled" },
  requires    = {},
  -- FEAT-14: no license needed; this is the open control-plane.
}
