-- CLUSTER-2 — installable manifest for the cluster Master daemon.
-- Run `pkg install cluster-master` after copying this directory tree
-- to a TOS repo location. The Master is the control-plane node; each
-- network should have exactly one. Multiple Masters would each accept
-- registrations independently and the cluster would partition.
--
-- Requires:
--   * A wireless modem (or a wired modem connected to every Manager).
--   * ROOT tier to operate the CLI's mutating subcommands.
--   * The `cluster-master` rc.d service stays disabled by default;
--     enable with `service start clusterd` after first install so an
--     accidentally-installed binary doesn't immediately start
--     advertising itself.
return {
  -- Generated by build-disk.lua (package integrity)
  hashes = {
    ["/etc/cluster-master.cfg"] = "ed2cf85983334e882a14c70be1bdccf25f6513a4603378a83cb0b78ca784688f",
    ["/etc/rc.d/clusterd.lua"] = "bf2ba84134dff8de1159902ddef19372795ec48abb7ac7a9673464a2ca2b5a53",
    ["/usr/bin/cluster.lua"] = "bae2ef0ed50b017b6bea901d6818b09b4476ba2174202f42f8dc7322aa51dfd8",
    ["/usr/lib/cluster/api.lua"] = "8d025085fae4d3aae35d40ede38216b67cdfafe0ffe7c0c2a7efd173c7b82ba1",
    ["/usr/lib/cluster/jobs.lua"] = "2bfd3f20f98f86718af51dcebfd4cdbd48a36022b7740013be7f9845e0bad461",
    ["/usr/lib/cluster/net.lua"] = "dffba8bdbcf1351824e54937b737b14ea12985f8cb560700b2d282a17936d342",
    ["/usr/lib/cluster/pair.lua"] = "4289bfc1fbbfd22b08151e71a883a8a163bce0acc7a3d098f8e660c5dafb1647",
    ["/usr/lib/cluster/scheduler.lua"] = "a62aba9da41e762856e2c25e7b0153ba3641e0591a1109b4f70a8742babc8192",
    ["/usr/lib/cluster/state.lua"] = "2a96d3f15ebe03f998b2ab56ec587baf63ab623df552d5fb5582f2610af457b0",
    ["/usr/lib/clusterd.lua"] = "ddb9a7d4ccff6191d9ef6ff634f882db1bac224157926b7fc6cbc5235eabddfe",
  },
  name        = "cluster-master",
  version     = "1.0.0",
  kind        = "service",
  category    = "network",
  description = "Cluster control-plane Master: registers Managers, schedules jobs, owns persistent state.",
  author      = "Strata Systems",
  files       = {
    "/usr/lib/clusterd.lua",
    "/usr/lib/cluster/state.lua",
    "/usr/lib/cluster/scheduler.lua",
    "/usr/lib/cluster/jobs.lua",
    "/usr/lib/cluster/net.lua",
    "/usr/lib/cluster/api.lua",
    "/usr/lib/cluster/pair.lua",
    "/usr/bin/cluster.lua",
    "/etc/rc.d/clusterd.lua",
    "/etc/cluster-master.cfg",
  },
  -- No `commands` map: the operator CLI ships as /usr/bin/cluster.lua and is
  -- run from PATH at full shell privilege (it needs the live kernel net/
  -- component surface, which the package sandbox would withhold). Declaring it
  -- as a package command would either be malformed (array form) or sandbox the
  -- CLI — so it is intentionally omitted, exactly like /usr/bin/servers, ssh.
  capabilities = {
    "fs.read", "fs.write",      -- /etc/cluster-master.cfg + /var/cluster/state.dat
    "component",                -- modem listing
    "peripheral.modem",         -- C4 split: cluster needs raw modem access
    "net",                      -- TOS net stack
    "load",                     -- evaluating job specs at submit time
  },
  -- The rc.d hook starts the daemon. defaultState=disabled so a fresh
  -- install doesn't auto-start a service on every machine that gets
  -- the package — operator decides per-host.
  service = { defaultState = "disabled" },
  requires    = {},
  -- FEAT-14: no license needed; this is the open control-plane.
}
